/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface SelectCity {
    }
    interface ShowName {
        "name": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSelectCityElement extends Components.SelectCity, HTMLStencilElement {
    }
    var HTMLSelectCityElement: {
        prototype: HTMLSelectCityElement;
        new (): HTMLSelectCityElement;
    };
    interface HTMLShowNameElement extends Components.ShowName, HTMLStencilElement {
    }
    var HTMLShowNameElement: {
        prototype: HTMLShowNameElement;
        new (): HTMLShowNameElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "select-city": HTMLSelectCityElement;
        "show-name": HTMLShowNameElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface SelectCity {
    }
    interface ShowName {
        "name"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "select-city": SelectCity;
        "show-name": ShowName;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "select-city": LocalJSX.SelectCity & JSXBase.HTMLAttributes<HTMLSelectCityElement>;
            "show-name": LocalJSX.ShowName & JSXBase.HTMLAttributes<HTMLShowNameElement>;
        }
    }
}
